### ISSUE TITLE
Encrypting on server and decrypting on device

### ISSUE THREAD

**Issue by hfossli** [satyamtyagi/swiftcrypto#3]
I read your blogpost. In it you say

> To encrypt data we will take a string message, encrypt it and then convert it to base64 encoded string such that it can be displayed. Note that the algorithm we are using for encryption is eciesEncryptionStandardX963SHA256AESGCM, which seems to be doing AES GCM encryption with SHA256 HMAC but the key we supplied was an ECC key. So what is happening? We are, in fact, doing exactly as the algorithm indicates (AES GCM SHA 256). But at the end, AES key is being encrypted by ECC public key (of the party we want to send the message to). This encrypted AES key is being sent along with the message.

Is it possible to encrypt server side using public key and then decrypt client side (on ios device) using private key? 

I would love to do the following
1. generate keypair on device
1. encrypt some data using openssl CLI and the public key 
1. decrypt on device using private key

Do you have any tips on how to achieve this?

**Comment by hfossli** [comment]
Basically I'm wondering how I can do this server side instead
```
encryptData = SecKeyCreateEncryptedData(newPublicKey, SecKeyAlgorithm.eciesEncryptionStandardX963SHA256AESGCM, messageData as CFData, nil)
```

**Comment by satyamtyagi** [comment]
Yes you should be able to do this with your choice of tool on server side (openssl etc)
You will have to first generate the key pair on iOS, extract and send the public key, send it as base 64 encode public key, there are standard export formats that iOS supports, "encrypt AES, append SHA hash", encrypt private key and send it to iOS to decrypt.

Also iOS does support doing this broken down specifically using RSA and  not DH and not using secure enclave

This blog explains this in detail, tricky thing when doing these step by step, you have to use some C code in iOS there are no direct Swift APIs on iOS

https://digitalleaves.com/blog/2015/10/asymmetric-cryptography-in-swift/

**Comment by satyamtyagi** [comment]
MIT license added
